### ISSUE TITLE
"pygments.util.ClassNotFound: no lexer for filename 'istream' found"

### ISSUE THREAD

**Issue by OfekShilon** [davidmalcolm/gcc-opt-viewer#4]
To reproduce: 
(1) 
```
$ git clone git@github.com:opencv/opencv.git opencv
$ cd opencv
$ export CXXFLAGS="-fsave-optimization-record"
$ mkdir build
$ cd build
$ cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=OFF -D OPENCV_GENERATE_PKGCONFIG=OFF -D BUILD_EXAMPLES=OFF  ..
$ make
```
(better not `make -jXX`, unless you build on a very powerful machine)
(2) from the gcc-opt-viewer folder:
```
./opt-viewer.py --output-dir <wherever> <opencv clone folder>/build/modules/photo
```

output (including my personal folders) is:
```
find_records: '/home/ofek/src/opencv_gcc/build/modules/photo'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_test_photo.dir/test/test_inpaint.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_test_photo.dir/test/test_decolor.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_test_photo.dir/test/test_denoising.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_test_photo.dir/test/test_npr.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_test_photo.dir/test/test_denoising.cuda.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_test_photo.dir/test/test_hdr.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_test_photo.dir/test/test_denoise_tvl1.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_test_photo.dir/test/test_cloning.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_test_photo.dir/test/test_main.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_test_photo.dir/test/ocl/test_denoising.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_perf_photo.dir/perf/perf_main.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_perf_photo.dir/perf/perf_inpaint.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_perf_photo.dir/perf/perf_cuda.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_perf_photo.dir/perf/opencl/perf_denoising.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_photo.dir/opencl_kernels_photo.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_photo.dir/src/npr.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_photo.dir/src/inpaint.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_photo.dir/src/denoise_tvl1.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_photo.dir/src/contrast_preserve.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_photo.dir/src/hdr_common.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_photo.dir/src/seamless_cloning.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_photo.dir/src/merge.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_photo.dir/src/tonemap.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_photo.dir/src/denoising.cuda.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_photo.dir/src/calibrate.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_photo.dir/src/seamless_cloning_impl.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_photo.dir/src/denoising.cpp.opt-record.json.gz'
 reading: '/home/ofek/src/opencv_gcc/build/modules/photo/CMakeFiles/opencv_photo.dir/src/align.cpp.opt-record.json.gz'
records by pass:
 slp: 263251
 vect: 115164
 einline: 71552
 inline: 18295
 lversion: 8349
 evrp: 2272
 cunrolli: 1381
 vrp: 1350
 dom: 1334
 pcom: 1029
 printf-return-value: 667
 ifcvt: 167
 ldist: 145
 devirt: 125
 cunroll: 66
 linterchange: 52
 cselim: 42
 ivopts: 23
 unrolljam: 18
 cp: 1
records by pass:
 vect: 115164
 einline: 71552
 inline: 18295
 lversion: 8349
 evrp: 2272
 vrp: 1350
 dom: 1334
 pcom: 1029
 printf-return-value: 667
 ifcvt: 167
 ldist: 145
 devirt: 125
 linterchange: 52
 cselim: 42
 ivopts: 23
 unrolljam: 18
 cp: 1
make_html
 analyze_counts
  purged 28143 non-precise records
 highest_count=70168500000
 make_index_html
 make_per_source_file_html
  generating HTML for '/home/ofek/src/opencv_gcc/modules/photo/test/test_inpaint.cpp'
  generating HTML for '/usr/include/c++/9/bits/basic_string.h'
  generating HTML for '/usr/include/c++/9/istream'
Traceback (most recent call last):
  File "./opt-viewer.py", line 17, in <module>
    generate_static_report(args.build_dir, args.output_dir)
  File "/home/ofek/src/gcc-opt-viewer/static.py", line 606, in generate_static_report
    make_html(build_dir, out_dir, tus)
  File "/home/ofek/src/gcc-opt-viewer/static.py", line 471, in make_html
    make_per_source_file_html(build_dir, out_dir, tus, highest_count)
  File "/home/ofek/src/gcc-opt-viewer/static.py", line 252, in make_per_source_file_html
    lexer = pygments.lexers.guess_lexer_for_filename(src_file, code)
  File "/usr/lib/python3/dist-packages/pygments/lexers/__init__.py", line 266, in guess_lexer_for_filename
    raise ClassNotFound('no lexer for filename %r found' % fn)
pygments.util.ClassNotFound: no lexer for filename 'istream' found
```

**Comment by OfekShilon** [comment]
The current code tries to guess a lexer from file extension. This doesn't work for C++ standard headers like <string>, <iostream> and the like.  

A workaround was implemented in: 
https://github.com/OfekShilon/gcc-opt-viewer/commit/5b5763a12ba922a3813fb237b89af33d9a3a9423
